export const QUERY_KEYS_RECOMMENDATIONS = {
  GET_RECOMMENDATIONS: 'GET_RECOMMENDATIONS',
  UPDATE_RECOMMENDATIONS: 'UPDATE_RECOMMENDATIONS',
  GET_CTAS: 'GET_CTAS',
  GET_RECOMMENDATIONS_COUNTER: 'GET_RECOMMENDATIONS_COUNTER'
};
